### ISSUE TITLE
Не получается запустить джарник после команды "java -jar ./artifacts/app-deadline.jar"

### ISSUE THREAD

**Issue by urii9158** [urii9158/SQL#1]
# Описание

Команда "docker compose up" отрабатывает нормально.

После команды "java -jar ./artifacts/app-deadline.jar -P:jdbc.url=jdbc:mysql://localhost:3306/db -P:jdbc.user=user -P:jdbc.password=password" выводится лишь часть информации и появляется ошибка:

 "Caused by: java.sql.SQLException: Unknown column 'status' in 'field list' Query: INSERT INTO users(id, login, password, status) VALUES (?, ?, ?, ?); Parameters: [77ce292e-b7c6-4edd-be4b-2c4db591b74f, vasya, $2a$10$igVgiTpHiNDdUU
lWDdU77ulwM0gs3ONKdhKF1d1rr/yj7xsIEg/ey, active]"

# Шаги воспроизведения

1. Запустить докер
2. Открыть терминал
3. Ввести "docker compose up"
4. Ввести "java -jar ./artifacts/app-deadline.jar -P:jdbc.url=jdbc:mysql://localhost:3306/db -P:jdbc.user=user -P:jdbc.password=password"

* Ожидаемый результат: Джарник запустился и вывел данные
* Фактический результат: Вывелась часть данных и появилась ошибка

# Логи сборки

<details>
<summary> java -jar ./artifacts/app-deadline.jar -P:jdbc.url=jdbc:mysql://localhost:3306/db -P:jdbc.user=user -P:jdbc.password=password
 </summary>

```txt
2024-08-04 19:06:29.172 [main] TRACE Application - {                                                                     
    # application.conf @ jar:file:/C:/Users/Home/IdeaProjects/sql/artifacts/app-deadline.jar!/application.conf: 6        
    "application" : {                                                                                                    
        # application.conf @ jar:file:/C:/Users/Home/IdeaProjects/sql/artifacts/app-deadline.jar!/application.conf: 7    
        "modules" : [                                                                                                    
            # application.conf @ jar:file:/C:/Users/Home/IdeaProjects/sql/artifacts/app-deadline.jar!/application.conf: 7
            "ru.netology.aqa.ApplicationKt.module"                                                                       
        ]                                                                                                                
    },                                                                                                                   
    # application.conf @ jar:file:/C:/Users/Home/IdeaProjects/sql/artifacts/app-deadline.jar!/application.conf: 2        
    "deployment" : {                                                                                                     
        # application.conf @ jar:file:/C:/Users/Home/IdeaProjects/sql/artifacts/app-deadline.jar!/application.conf: 3    
        "port" : 9999                                                                                                    
    },
    # Content hidden
    "security" : "***"
}

2024-08-04 19:06:29.243 [DefaultDispatcher-worker-1] INFO  Application - No ktor.deployment.watch patterns specified, automatic reload is not active
Exception in thread "DefaultDispatcher-worker-1" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:152)
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:392)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:340)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:287)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:320)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:286)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:302)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:284)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:137)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:257)
        at io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(CIOApplicationEngine.kt:52)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by: java.sql.SQLException: Unknown column 'status' in 'field list' Query: INSERT INTO users(id, login, password, status) VALUES (?, ?, ?, ?); Parameters: [77ce292e-b7c6-4edd-be4b-2c4db591b74f, vasya, $2a$10$igVgiTpHiNDdUU
lWDdU77ulwM0gs3ONKdhKF1d1rr/yj7xsIEg/ey, active]
        at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:527)
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:531)
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:497)
        at ru.netology.aqa.service.UserService$register$2.invokeSuspend(UserService.kt:31)
        ... 5 more
```

</details>

# Скриншот 

![Screenshot_25](https://github.com/user-attachments/assets/1ab67243-1214-4664-ab95-88d5596edc47)
![Screenshot_26](https://github.com/user-attachments/assets/31cd1637-3203-43a5-8320-e9183f226c15)

# Окружение

* **Операционная система:**  Windows 10 Pro 22H2 x64
* **IDE:** Intellij IDEA Community Edition 2023.3.4
* **Java:** OpenJDK 11
* **Исходник проекта:** netology.ru

**Comment by andrew-pahomov** [comment]
Добрый день 

Прошу показать скрины с полными логами. В текущем фрагменте нет причины падения.

**Comment by urii9158** [comment]
Здравствуйте

Полные логи изначально добавила в "Логи сборки", скриншоты обновила

**Comment by andrew-pahomov** [comment]
Не могу повторить описанную в issue ошибку. Есть подозрение, что на вашей машине локально установлена СУБД MySQL, если это так, то прошу её удалить. Если СУБД не установлена, то надо искать приложения, блокирующие доступ к контейнеру. Возможно это брандмауэр или антивирус.

**Comment by urii9158** [comment]
Здравствуйте

СУБД MySQL не установлена, я проверяла двумя способами.
Брандмаузер я дополнительно настроила, антивирус отключила, не помогло, как дальше выполнять задание?

**Comment by andrew-pahomov** [comment]
Могу только порекомендовать поиск приложения, блокирующего доступ к контейнеру с базой. Можете также попробовать пробросить порт базы на другой порт, отличный от 3306.
